name: device-manager

x-pg-mdb-credentials: &pg-mdb-credentials
  MYSQL_USER: maria_db
  MYSQL_PASSWORD: maria_db
  MYSQL_DATABASE: device_manager
  MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
  LANG: C.UTF-8

services:
  database:
    image: mariadb:11.3.2
    container_name: device-manager-dev-db
    ports:
      - "3306:3306"
    volumes:
      - device-manager-dev-db:/var/lib/postgresql/data
    environment:
      <<: *pg-mdb-credentials

volumes:
  device-manager-dev-db:
