# Generated by Django 5.0.4 on 2024-04-20 21:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name_decoration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.displaynamedecorator",
                verbose_name="Degree",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telephone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region="PL"),
        ),
        migrations.AlterField(
            model_name="user",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
