# Generated by Django 5.0.4 on 2024-05-11 21:32

from django.db import migrations

import devicemanager.helpers.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_name_decoration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_preferences",
            field=devicemanager.helpers.fields.DictJSONField(default=dict, verbose_name="User preferences"),
        ),
    ]
