# Generated by Django 5.0.4 on 2024-05-12 00:38

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, verbose_name="Model Name")),
                ("description", models.TextField(blank=True, verbose_name="Device Description")),
            ],
            options={
                "verbose_name": "Device Model",
                "verbose_name_plural": "Device Models",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=512, null=True, unique=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=512,
                        null=True,
                        unique=True,
                        verbose_name="Inventory Number",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="inventory.devicemodel",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, verbose_name="Device Type Name")),
                ("short_name", models.CharField(max_length=60, verbose_name="Device short name")),
            ],
            options={
                "verbose_name": "Device Type",
                "verbose_name_plural": "Device Types",
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("short_name"), name="device_type_sname_lower_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="inventory.devicetype",
                verbose_name="Device Type",
            ),
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=512, unique=True, verbose_name="Faculty Full Name")),
                ("short_name", models.CharField(max_length=60, unique=True, verbose_name="Faculty  Name")),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "indexes": [
                    models.Index(django.db.models.functions.text.Lower("short_name"), name="faculty_name_lower_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60, verbose_name="Building Name")),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="buildings", to="inventory.faculty"
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="Manufacturer Name")),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "indexes": [
                    models.Index(django.db.models.functions.text.Lower("name"), name="manufacturer_name_lower_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="inventory.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=60, verbose_name="Room Number")),
                ("description", models.TextField(blank=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="inventory.building",
                        verbose_name="Building",
                    ),
                ),
                (
                    "occupants",
                    models.ManyToManyField(
                        blank=True, related_name="rooms", to=settings.AUTH_USER_MODEL, verbose_name="Occupants"
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(django.db.models.functions.text.Lower("name"), name="building_name_lower_idx"),
        ),
        migrations.AddIndex(
            model_name="devicemodel",
            index=models.Index(django.db.models.functions.text.Lower("name"), name="device_model_name_lower_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(django.db.models.functions.text.Lower("room_number"), name="room_number_lower_idx"),
        ),
    ]
