# Generated by Django 5.0.4 on 2024-05-12 15:05

import colorfield.fields
import django_lifecycle.mixins
from django.db import migrations, models

import devicemanager.inventory.models
import devicemanager.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCodeGenerationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, verbose_name="QR Code Generation Config ID"),
                ),
                ("qr_code_size_cm", models.PositiveIntegerField(default=5, verbose_name="QR Code Size in cm")),
                ("qr_code_margin_mm", models.PositiveIntegerField(default=3, verbose_name="QR Code Margin")),
                ("active", models.BooleanField(default=False, verbose_name="Configuration in use")),
                (
                    "fill_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=25, samples=None, verbose_name="Fill Color"
                    ),
                ),
                (
                    "back_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Background Color",
                    ),
                ),
                (
                    "serial_number_label",
                    models.CharField(default="SN", max_length=15, verbose_name="Serial Number Label"),
                ),
                (
                    "inventory_number_label",
                    models.CharField(default="IN", max_length=15, verbose_name="Inventory Number Label"),
                ),
                ("id_label", models.CharField(default="ID", max_length=15, verbose_name="ID Label")),
                (
                    "included_labels",
                    devicemanager.utils.fields.ListJSONField(
                        default=devicemanager.inventory.models.Device.default_labels_include,
                        verbose_name="Included Labels",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Generation Config",
                "verbose_name_plural": "QR Code Generation Configs",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
