# Generated by Django 5.0.4 on 2024-05-13 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_qrcodegenerationconfig_pdf_page_height_mm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceRental",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rental_date", models.DateField(auto_now_add=True, verbose_name="Rental Date")),
                ("return_date", models.DateField(blank=True, null=True, verbose_name="Return Date")),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Borrower",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="inventory.device",
                        verbose_name="Device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Rental",
                "verbose_name_plural": "Device Rentals",
            },
        ),
    ]
