# Generated by Django 5.0.4 on 2024-05-27 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_devicerental"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="model",
            new_name="device_model",
        ),
    ]
