# Generated by Django 5.0.4 on 2024-06-03 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_device_guardian_device_room"),
        ("inventory", "0005_rename_model_device_device_model"),
    ]

    operations = []
