# Generated by Django 5.0.4 on 2024-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_merge_20240603_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="inventory_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True, verbose_name="Inventory Number"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name="Serial Number"),
        ),
    ]
