# Generated by Django 5.0.4 on 2024-06-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_remove_unique_on_inv_number_and_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="building_label",
            field=models.CharField(blank=True, default="", max_length=15, verbose_name="Building Label"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="owner_label",
            field=models.CharField(blank=True, default="", max_length=15, verbose_name="Owner Label"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="room_label",
            field=models.CharField(blank=True, default="", max_length=15, verbose_name="Room Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="inventory_number_label",
            field=models.CharField(blank=True, default="IN", max_length=15, verbose_name="Inventory Number Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="serial_number_label",
            field=models.CharField(blank=True, default="SN", max_length=15, verbose_name="Serial Number Label"),
        ),
    ]
