# Generated by Django 5.0.4 on 2024-06-10 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_qrcodegenerationconfig_building_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="id_label",
        ),
    ]
