# Generated by Django 5.0.4 on 2024-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_qrcodegenerationconfig_building_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="building_label",
            field=models.CharField(default="Building", max_length=15, verbose_name="Building Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="owner_label",
            field=models.CharField(default="Owner", max_length=15, verbose_name="Owner Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="room_label",
            field=models.CharField(default="Room", max_length=15, verbose_name="Room Label"),
        ),
    ]
