# Generated by Django 5.0.4 on 2024-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_qrcodegenerationconfig_building_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetype",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Device Type"),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="short_name",
            field=models.CharField(max_length=60, verbose_name="Device Type short name"),
        ),
    ]
