# Generated by Django 5.0.4 on 2024-06-13 19:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_qrcodegenerationconfig_building_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicerental",
            name="rental_date",
            field=models.DateField(default=datetime.datetime.now, verbose_name="Rental Date"),
        ),
    ]
