# Generated by Django 5.0.4 on 2024-06-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_devicerental_rental_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="building_label",
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="device_model_label",
            field=models.CharField(default="Model", max_length=15, verbose_name="Model Label"),
        ),
    ]
