# Generated by Django 5.0.4 on 2024-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_remove_qrcodegenerationconfig_building_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="device_model_label",
            field=models.CharField(blank=True, default="Model", max_length=15, null=True, verbose_name="Model Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="inventory_number_label",
            field=models.CharField(
                blank=True, default="IN", max_length=15, null=True, verbose_name="Inventory Number Label"
            ),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="owner_label",
            field=models.CharField(blank=True, default="Owner", max_length=15, null=True, verbose_name="Owner Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="room_label",
            field=models.CharField(blank=True, default="Room", max_length=15, null=True, verbose_name="Room Label"),
        ),
        migrations.AlterField(
            model_name="qrcodegenerationconfig",
            name="serial_number_label",
            field=models.CharField(
                blank=True, default="SN", max_length=15, null=True, verbose_name="Serial Number Label"
            ),
        ),
    ]
