# Generated by Django 5.0.4 on 2024-06-13 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_devicetype_name_alter_devicetype_short_name"),
        ("inventory", "0014_alter_qrcodegenerationconfig_device_model_label_and_more"),
    ]

    operations = []
