# Generated by Django 5.0.4 on 2024-06-15 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_merge_20240613_2048"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrcodegenerationconfig",
            old_name="back_color",
            new_name="background_color",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="device_model_label",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="included_labels",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="inventory_number_label",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="owner_label",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="pdf_page_height_mm",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="pdf_page_width_mm",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="print_dpi",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="qr_code_margin_mm",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="qr_code_size_cm",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="room_label",
        ),
        migrations.RemoveField(
            model_name="qrcodegenerationconfig",
            name="serial_number_label",
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="dpi",
            field=models.PositiveIntegerField(
                default=300, validators=[django.core.validators.MinValueValidator(1)], verbose_name="DPI"
            ),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="font_size",
            field=models.PositiveIntegerField(default=18, verbose_name="Font Size [pt]"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="font_size_large",
            field=models.PositiveIntegerField(default=28, verbose_name="Large Font Size [pt]"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="font_size_small",
            field=models.PositiveIntegerField(default=14, verbose_name="Small Font Size [pt]"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="inv_prefix",
            field=models.CharField(
                blank=True, default="inv:", max_length=15, null=True, verbose_name="Inventory Number Prefix"
            ),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="label_height_mm",
            field=models.PositiveIntegerField(
                default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Label Height in mm"
            ),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="label_horizontal_spacing_mm",
            field=models.PositiveIntegerField(default=2, verbose_name="Label Horizontal Spacing in mm"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="label_padding_mm",
            field=models.PositiveIntegerField(default=2, verbose_name="Label Padding in mm"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="label_title_gap_mm",
            field=models.PositiveIntegerField(
                default=2, verbose_name="Label gap between room and rest of the fields in mm"
            ),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="label_vertical_spacing_mm",
            field=models.PositiveIntegerField(default=1, verbose_name="Label Vertical Spacing in mm"),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="label_width_mm",
            field=models.PositiveIntegerField(
                default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Label Width in mm"
            ),
        ),
        migrations.AddField(
            model_name="qrcodegenerationconfig",
            name="sn_prefix",
            field=models.CharField(
                blank=True, default="sn:", max_length=15, null=True, verbose_name="Serial Number Prefix"
            ),
        ),
    ]
