# Generated by Django 5.0.4 on 2024-06-15 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_rename_back_color_qrcodegenerationconfig_background_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="guardian",
            new_name="owner",
        ),
    ]
